package hu.bankmonitor.starter.microservice.common.errorhandling;

public enum ExceptionType {

	EVENT_CLASS_FINDER_CLASS_LOADING_ERROR, EVENT_CLASS_FINDER_FIND_EVENT_CLASSES_ERROR, EVENT_CLASS_FINDER_WRONG_METHOD_SIGNITURE, RABBITMQ_RPC_INIT_ERROR, RABBITMQ_MESSAGE_HANDLING_ERROR, UNKNOWN_ERROR;

}
